### ISSUE TITLE
Ver si se puede mejorar la búsqueda de producto (lista no demasiado larga)

### ISSUE THREAD

**Issue by rodrigoherera** [rodrigoherera/ProyectoFinal#13]

**Comment by rodrigoherera** [comment]
Queda pendiente para reúnion de consorcio del próximo lúnes. 

> 21/05/2015

**Comment by GabrielAMantei** [comment]
Se rediseñó el ABM de producto. Se modificó la representación, con lo cual cambió la problemática inicial.
