### ISSUE TITLE
Falla: Guardar Categoria

### ISSUE THREAD

**Issue by GabrielAMantei** [rodrigoherera/ProyectoFinal#27]
Error al guardar una nueva categoria:
_Error converting data type varchar to int._
Ventana **frmPanelCategoria**
Boton **btn_Guardar**
Metodo **btn_Guardar_Click**

**Comment by rodrigoherera** [comment]
Fallaba por el agregado del campo Descripción pero no se hago el control/Objeto Descripción.
De momento se envia vacio a la DB, pero si se está bien de tiempo, habría que asociarla con un objeto y enviarle ese valor, no vacio.
