### ISSUE TITLE
O.C -> carga categorias discontinuadas

### ISSUE THREAD

**Issue by eltano89** [rodrigoherera/ProyectoFinal#45]
si una categoria esta discontinuadas no deberia traer productos

**Comment by GabrielAMantei** [comment]
No encuentro este error ¿Donde esta pasando eso?

**Comment by rodrigoherera** [comment]
Sucede en las Ordenes de compra.
Cuando se discontinua una categoría, no debería de mostrarlas.

**Comment by GabrielAMantei** [comment]
Corregido.
El verdadero problema esta en la modificacion de categoria, que duplica la modificada (deshabilitada), por lo que la original nunca queda deshabilitada.
Se abre un issue nuevo para el bug correspondiente.
